// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nats_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_nats_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_nats_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "rpc_msg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_nats_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_nats_5fmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nats_5fmsg_2eproto;
namespace nats_msg {
class NATS_MSG_PRXOY;
class NATS_MSG_PRXOYDefaultTypeInternal;
extern NATS_MSG_PRXOYDefaultTypeInternal _NATS_MSG_PRXOY_default_instance_;
}  // namespace nats_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::nats_msg::NATS_MSG_PRXOY* Arena::CreateMaybeMessage<::nats_msg::NATS_MSG_PRXOY>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace nats_msg {

// ===================================================================

class NATS_MSG_PRXOY :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:nats_msg.NATS_MSG_PRXOY) */ {
 public:
  NATS_MSG_PRXOY();
  virtual ~NATS_MSG_PRXOY();

  NATS_MSG_PRXOY(const NATS_MSG_PRXOY& from);
  NATS_MSG_PRXOY(NATS_MSG_PRXOY&& from) noexcept
    : NATS_MSG_PRXOY() {
    *this = ::std::move(from);
  }

  inline NATS_MSG_PRXOY& operator=(const NATS_MSG_PRXOY& from) {
    CopyFrom(from);
    return *this;
  }
  inline NATS_MSG_PRXOY& operator=(NATS_MSG_PRXOY&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NATS_MSG_PRXOY& default_instance();

  enum MsgCase {
    kRpcRequest = 100,
    kRpcResponse = 101,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NATS_MSG_PRXOY* internal_default_instance() {
    return reinterpret_cast<const NATS_MSG_PRXOY*>(
               &_NATS_MSG_PRXOY_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NATS_MSG_PRXOY& a, NATS_MSG_PRXOY& b) {
    a.Swap(&b);
  }
  inline void Swap(NATS_MSG_PRXOY* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NATS_MSG_PRXOY* New() const final {
    return CreateMaybeMessage<NATS_MSG_PRXOY>(nullptr);
  }

  NATS_MSG_PRXOY* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NATS_MSG_PRXOY>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NATS_MSG_PRXOY& from);
  void MergeFrom(const NATS_MSG_PRXOY& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NATS_MSG_PRXOY* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "nats_msg.NATS_MSG_PRXOY";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_nats_5fmsg_2eproto);
    return ::descriptor_table_nats_5fmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRpcTypeFieldNumber = 1,
    kRpcRequestFieldNumber = 100,
    kRpcResponseFieldNumber = 101,
  };
  // uint32 rpc_type = 1;
  void clear_rpc_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 rpc_type() const;
  void set_rpc_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rpc_type() const;
  void _internal_set_rpc_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // .rpc_msg.RPC_REQUEST rpc_request = 100;
  bool has_rpc_request() const;
  private:
  bool _internal_has_rpc_request() const;
  public:
  void clear_rpc_request();
  const ::rpc_msg::RPC_REQUEST& rpc_request() const;
  ::rpc_msg::RPC_REQUEST* release_rpc_request();
  ::rpc_msg::RPC_REQUEST* mutable_rpc_request();
  void set_allocated_rpc_request(::rpc_msg::RPC_REQUEST* rpc_request);
  private:
  const ::rpc_msg::RPC_REQUEST& _internal_rpc_request() const;
  ::rpc_msg::RPC_REQUEST* _internal_mutable_rpc_request();
  public:

  // .rpc_msg.RPC_RESPONSE rpc_response = 101;
  bool has_rpc_response() const;
  private:
  bool _internal_has_rpc_response() const;
  public:
  void clear_rpc_response();
  const ::rpc_msg::RPC_RESPONSE& rpc_response() const;
  ::rpc_msg::RPC_RESPONSE* release_rpc_response();
  ::rpc_msg::RPC_RESPONSE* mutable_rpc_response();
  void set_allocated_rpc_response(::rpc_msg::RPC_RESPONSE* rpc_response);
  private:
  const ::rpc_msg::RPC_RESPONSE& _internal_rpc_response() const;
  ::rpc_msg::RPC_RESPONSE* _internal_mutable_rpc_response();
  public:

  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:nats_msg.NATS_MSG_PRXOY)
 private:
  class _Internal;
  void set_has_rpc_request();
  void set_has_rpc_response();

  inline bool has_msg() const;
  inline void clear_has_msg();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rpc_type_;
  union MsgUnion {
    MsgUnion() {}
    ::rpc_msg::RPC_REQUEST* rpc_request_;
    ::rpc_msg::RPC_RESPONSE* rpc_response_;
  } msg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_nats_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NATS_MSG_PRXOY

// uint32 rpc_type = 1;
inline void NATS_MSG_PRXOY::clear_rpc_type() {
  rpc_type_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NATS_MSG_PRXOY::_internal_rpc_type() const {
  return rpc_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NATS_MSG_PRXOY::rpc_type() const {
  // @@protoc_insertion_point(field_get:nats_msg.NATS_MSG_PRXOY.rpc_type)
  return _internal_rpc_type();
}
inline void NATS_MSG_PRXOY::_internal_set_rpc_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rpc_type_ = value;
}
inline void NATS_MSG_PRXOY::set_rpc_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rpc_type(value);
  // @@protoc_insertion_point(field_set:nats_msg.NATS_MSG_PRXOY.rpc_type)
}

// .rpc_msg.RPC_REQUEST rpc_request = 100;
inline bool NATS_MSG_PRXOY::_internal_has_rpc_request() const {
  return msg_case() == kRpcRequest;
}
inline bool NATS_MSG_PRXOY::has_rpc_request() const {
  return _internal_has_rpc_request();
}
inline void NATS_MSG_PRXOY::set_has_rpc_request() {
  _oneof_case_[0] = kRpcRequest;
}
inline ::rpc_msg::RPC_REQUEST* NATS_MSG_PRXOY::release_rpc_request() {
  // @@protoc_insertion_point(field_release:nats_msg.NATS_MSG_PRXOY.rpc_request)
  if (_internal_has_rpc_request()) {
    clear_has_msg();
      ::rpc_msg::RPC_REQUEST* temp = msg_.rpc_request_;
    msg_.rpc_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rpc_msg::RPC_REQUEST& NATS_MSG_PRXOY::_internal_rpc_request() const {
  return _internal_has_rpc_request()
      ? *msg_.rpc_request_
      : *reinterpret_cast< ::rpc_msg::RPC_REQUEST*>(&::rpc_msg::_RPC_REQUEST_default_instance_);
}
inline const ::rpc_msg::RPC_REQUEST& NATS_MSG_PRXOY::rpc_request() const {
  // @@protoc_insertion_point(field_get:nats_msg.NATS_MSG_PRXOY.rpc_request)
  return _internal_rpc_request();
}
inline ::rpc_msg::RPC_REQUEST* NATS_MSG_PRXOY::_internal_mutable_rpc_request() {
  if (!_internal_has_rpc_request()) {
    clear_msg();
    set_has_rpc_request();
    msg_.rpc_request_ = CreateMaybeMessage< ::rpc_msg::RPC_REQUEST >(
        GetArenaNoVirtual());
  }
  return msg_.rpc_request_;
}
inline ::rpc_msg::RPC_REQUEST* NATS_MSG_PRXOY::mutable_rpc_request() {
  // @@protoc_insertion_point(field_mutable:nats_msg.NATS_MSG_PRXOY.rpc_request)
  return _internal_mutable_rpc_request();
}

// .rpc_msg.RPC_RESPONSE rpc_response = 101;
inline bool NATS_MSG_PRXOY::_internal_has_rpc_response() const {
  return msg_case() == kRpcResponse;
}
inline bool NATS_MSG_PRXOY::has_rpc_response() const {
  return _internal_has_rpc_response();
}
inline void NATS_MSG_PRXOY::set_has_rpc_response() {
  _oneof_case_[0] = kRpcResponse;
}
inline ::rpc_msg::RPC_RESPONSE* NATS_MSG_PRXOY::release_rpc_response() {
  // @@protoc_insertion_point(field_release:nats_msg.NATS_MSG_PRXOY.rpc_response)
  if (_internal_has_rpc_response()) {
    clear_has_msg();
      ::rpc_msg::RPC_RESPONSE* temp = msg_.rpc_response_;
    msg_.rpc_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::rpc_msg::RPC_RESPONSE& NATS_MSG_PRXOY::_internal_rpc_response() const {
  return _internal_has_rpc_response()
      ? *msg_.rpc_response_
      : *reinterpret_cast< ::rpc_msg::RPC_RESPONSE*>(&::rpc_msg::_RPC_RESPONSE_default_instance_);
}
inline const ::rpc_msg::RPC_RESPONSE& NATS_MSG_PRXOY::rpc_response() const {
  // @@protoc_insertion_point(field_get:nats_msg.NATS_MSG_PRXOY.rpc_response)
  return _internal_rpc_response();
}
inline ::rpc_msg::RPC_RESPONSE* NATS_MSG_PRXOY::_internal_mutable_rpc_response() {
  if (!_internal_has_rpc_response()) {
    clear_msg();
    set_has_rpc_response();
    msg_.rpc_response_ = CreateMaybeMessage< ::rpc_msg::RPC_RESPONSE >(
        GetArenaNoVirtual());
  }
  return msg_.rpc_response_;
}
inline ::rpc_msg::RPC_RESPONSE* NATS_MSG_PRXOY::mutable_rpc_response() {
  // @@protoc_insertion_point(field_mutable:nats_msg.NATS_MSG_PRXOY.rpc_response)
  return _internal_mutable_rpc_response();
}

inline bool NATS_MSG_PRXOY::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void NATS_MSG_PRXOY::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline NATS_MSG_PRXOY::MsgCase NATS_MSG_PRXOY::msg_case() const {
  return NATS_MSG_PRXOY::MsgCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace nats_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_nats_5fmsg_2eproto
