// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opcodes.proto

#include "opcodes.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace opcodes {
}  // namespace opcodes
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_opcodes_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_opcodes_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_opcodes_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_opcodes_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_opcodes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ropcodes.proto\022\007opcodes*\241\003\n\tOPCODE_ID\022\013"
  "\n\007OP_None\020\000\022.\n*OP_DISCOVERY_MSG_REQUEST_"
  "REGISTER_INSTANCE\020e\022+\n\'OP_DISCOVERY_MSG_"
  "RESP_REGISTER_INSTANCE\020f\022$\n OP_DISCOVERY"
  "_MSG_NOTICE_INSTANCE\020g\022&\n\"OP_DISCOVERY_M"
  "SG_REQUEST_HEARTBEAT\020h\022#\n\037OP_DISCOVERY_M"
  "SG_RESP_HEARTBEAT\020i\022#\n\036OP_ROUTE_MSG_REQU"
  "EST_ADD_ROUTE\020\311\001\022 \n\033OP_ROUTE_MSG_RESP_AD"
  "D_ROUTE\020\312\001\022#\n\036OP_ROUTE_MSG_REQUEST_HEART"
  "BEAT\020\313\001\022 \n\033OP_ROUTE_MSG_RESP_HEARTBEAT\020\314"
  "\001\022\023\n\016OP_RPC_REQUEST\020\255\002\022\024\n\017OP_RPC_RESPONS"
  "E\020\256\002*\366\005\n\nStatusCode\022\t\n\005SC_Ok\020\000\022\032\n\026SC_Dis"
  "covery_AuthError\020d\022\036\n\032SC_Discovery_Dupli"
  "cateNode\020e\022\035\n\031SC_Discovery_Unregistered\020"
  "f\022 \n\034SC_Discovery_ServerListEmpty\020g\022\035\n\031S"
  "C_Discovery_InvalidPoint\020h\022\032\n\025SC_Route_I"
  "nvalidPoint\020\310\001\022\027\n\022SC_Route_AuthError\020\311\001\022"
  "\032\n\025SC_Route_Unregistered\020\312\001\022\023\n\016SC_Rpc_Ti"
  "meout\020\254\002\022\026\n\021SC_Rpc_RouteEmpty\020\255\002\022!\n\034SC_R"
  "pc_RouteEstablishedEmpty\020\256\002\022!\n\034SC_Rpc_Ro"
  "uteSerialNumInvalid\020\257\002\022\032\n\025SC_Rpc_RouteSe"
  "ndError\020\260\002\022\034\n\027SC_Rpc_NotReceivedReply\020\261\002"
  "\022\023\n\016SC_Rpc_NotSend\020\262\002\022$\n\037SC_Rpc_InvalidA"
  "rgs_MethodsEmpty\020\263\002\022\031\n\024SC_Rpc_Partial_Er"
  "ror\020\264\002\022&\n!SC_ClientProxy_SerialNumEqualZ"
  "ero\020\220\003\022)\n$SC_ClientProxy_SerialNumNotEqu"
  "alZero\020\221\003\022\037\n\032SC_ClientProxy_Established\020"
  "\222\003\022\"\n\035SC_ClientProxy_NotEstablished\020\223\003\022\034"
  "\n\027SC_ClientProxy_BadAlloc\020\224\003\022\036\n\031SC_Clien"
  "tProxy_NoIOThread\020\225\003\022\027\n\022SC_BindTable_Err"
  "or\020\364\003b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_opcodes_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_opcodes_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_opcodes_2eproto_once;
static bool descriptor_table_opcodes_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_opcodes_2eproto = {
  &descriptor_table_opcodes_2eproto_initialized, descriptor_table_protodef_opcodes_2eproto, "opcodes.proto", 1213,
  &descriptor_table_opcodes_2eproto_once, descriptor_table_opcodes_2eproto_sccs, descriptor_table_opcodes_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_opcodes_2eproto::offsets,
  file_level_metadata_opcodes_2eproto, 0, file_level_enum_descriptors_opcodes_2eproto, file_level_service_descriptors_opcodes_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_opcodes_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_opcodes_2eproto), true);
namespace opcodes {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OPCODE_ID_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_opcodes_2eproto);
  return file_level_enum_descriptors_opcodes_2eproto[0];
}
bool OPCODE_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 201:
    case 202:
    case 203:
    case 204:
    case 301:
    case 302:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatusCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_opcodes_2eproto);
  return file_level_enum_descriptors_opcodes_2eproto[1];
}
bool StatusCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
    case 200:
    case 201:
    case 202:
    case 300:
    case 301:
    case 302:
    case 303:
    case 304:
    case 305:
    case 306:
    case 307:
    case 308:
    case 400:
    case 401:
    case 402:
    case 403:
    case 404:
    case 405:
    case 500:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace opcodes
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
